### ISSUE TITLE
PyGame - Intro

### ISSUE THREAD

**Issue by peey** [IIIT-Delhi/talks#17]
Probably should host it in winter session.

**Target Audience:** All of first years, now proficient with python. Even the people may not have attended many Byld sessions in monsson due to unfamiliarity with python

**Comment by chirag-jn** [comment]
I would like to host the session.

**Comment by amehra-github** [comment]
I am would like join as well. @chirag-jn  if you are fine we could cohost

**Comment by chirag-jn** [comment]
Works for me.

**Comment by peey** [comment]
@chirag-jn and @amehra-github will be cohosting this tentatively on 22nd
