### ISSUE TITLE
Typo in Byld Hackathon v14 README.md

### ISSUE THREAD

**Issue by geekSiddharth** [IIIT-Delhi/talks#21]
We need to replace `Sharmishtha` with `Sharmistha` in [this file](https://github.com/IIIT-Delhi/talks/blob/master/hackathon14/README.md).

**Comment by aishna2502** [comment]
I would like to take this up as I want to get some hands on with PRs.

**Comment by geekSiddharth** [comment]
Go on!

**Comment by geekSiddharth** [comment]
@aishna2502 Sorry! This issue has been fixed by the person whose name had the typo.
