### ISSUE TITLE
Byld Hackathon v15

### ISSUE THREAD

**Issue by sedflix** [IIIT-Delhi/talks#31]

**Comment by peey** [comment]
What's the idea with opening this? Usual idea is that we invite speakers, and discuss details for the talk on the issue. 

This issue for inviting suggestions for the hack?

**Comment by geekSiddharth** [comment]
I thought having all the events we organize in one place would be nice. More kind of design thing. 

And yes to inviting suggestions for the hack.

**Comment by sedflix** [comment]
#39
