### ISSUE TITLE
Darwin Dev

### ISSUE THREAD

**Issue by chirag-jn** [IIIT-Delhi/talks#4]
Can we have another Darwin Dev competition?

**Comment by geekSiddharth** [comment]
One coming up after the mid sems.

**Comment by chirag-jn** [comment]
Oh cool

**Comment by geekSiddharth** [comment]
Any API/topics which you guys wanna suggest?

**Comment by Aniket-Pradhan** [comment]
How about the Slack API, or the NASA API. You can do a lot of things using either of them. Like, building a bot which gives you a weekly digest (for slack), or an app which gives you the NASA picture of the day, weather reports, or something like that.
